// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_dc455.Models;

namespace Mission06_dc455.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    [Migration("20230214042209_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_dc455.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("EntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            EntryID = 1,
                            Category = "Action/Adventure",
                            Director = "Peter Jackson",
                            Edited = false,
                            Notes = "Best battle ever!",
                            Rating = "PG-13",
                            Title = "The Lord of the Rings: The Two Towers",
                            Year = 2004
                        },
                        new
                        {
                            EntryID = 2,
                            Category = "Action/Adventure",
                            Director = "Joe/Anthony Russo",
                            Edited = false,
                            Notes = "Dope movie",
                            Rating = "PG-13",
                            Title = "The Gray Man",
                            Year = 2022
                        },
                        new
                        {
                            EntryID = 3,
                            Category = "Action/Adventure",
                            Director = "Martin Campbell",
                            Edited = false,
                            Notes = "GOAT",
                            Rating = "PG-13",
                            Title = "Casino Royale",
                            Year = 2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
